name: callkeep
description: iOS CallKit framework and Android ConnectionService for Flutter.
version: 0.2.4
homepage: https://github.com/flutter-webrtc/callkeep

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.cloudwebrtc.flutter_callkeep
        pluginClass: FlutterCallkeepPlugin
      ios:
        pluginClass: FlutterCallkeepPlugin
